### PR TITLE
fix: Issue 831 image cors order issue

### PR DESCRIPTION
**Pull request by ThibaultJanBeyer**
This PR will fix https://github.com/microsoft/VoTT/issues/831
Where the `crossOrigin` attribute order was wrong.

### CODE REVIEW

**Comment by tbarlow12** [comment]
@ThibaultJanBeyer please re-target your PR to the `develop` branch

**Comment by ThibaultJanBeyer** [comment]
Ok currently very busy but will do as soon as I've time

**Comment by ThibaultJanBeyer** [comment]
Been there, done that

**Comment by ThibaultJanBeyer** [comment]
:/

**Pull request closed without merging**
