### PR TITLE
feat: Korean language support 

### PR DESCRIPTION
**Pull request by aykhara**
Korean translation verified by @angie4u

### CODE REVIEW

**Comment by aykhara** [comment]
@mydiemho Thank you for taking the time to review this. Yes, I have built the app locally and worked correctly with all the strings on my side.

**Comment by angie4u** [comment]
Yeap! I also checked my side as well and it works fine! :) 
I'm adding few screenshots on this ;)
image

image

image

image

**Comment by mydiemho** [comment]
Codecov is having issues updating GitHub again.  Going to bypass and merge since the report show that coverage report is good https://codecov.io/gh/microsoft/VoTT/tree/058354be8e1be7a9a01b9f38314ebb2055796a39

**Pull request merged**
